"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import RepoLensSidebar from "@/components/RepoLensSidebar";
import { getRepositoryDrift, type RepositoryDrift } from "@/lib/api";

export default function DriftPage() {
 const [data,setData]=useState<RepositoryDrift|null>(null); const [error,setError]=useState("");
 useEffect(()=>{getRepositoryDrift().then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load drift analysis."));},[]);
 const d=data?.drift;
 return <main className="min-h-screen repolens-page repolens-route-drift bg-[#050505] text-white"><div className="flex min-h-screen flex-col lg:flex-row"><RepoLensSidebar/><section className="min-w-0 flex-1"><header className="border-b border-white/[.07] px-6 py-5 lg:px-9"><div className="text-[10px] uppercase tracking-[.2em] text-indigo-300/60">History / Drift</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em]">Architecture drift</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/40">Deterministic comparison of the two newest persisted architecture snapshots. No baseline means no fabricated drift result.</p></header><div className="mx-auto max-w-[1380px] px-6 py-8 lg:px-9">{error&&<Alert text={error}/>} {!data&&!error&&<Skeleton/>} {data&&<><div className="grid gap-4 md:grid-cols-3"><Stat label="Status" value={data.status==='ready'?'Comparison ready':'Baseline needed'}/><Stat label="Modules added" value={d?.module_drift.added_count??'—'}/><Stat label="Modules removed" value={d?.module_drift.removed_count??'—'}/></div>{data.status==='ready'&&d?<><div className="mt-6 rounded-3xl border border-indigo-300/10 bg-white/[.025] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.18em] text-white/30">Comparison result</div><div className="mt-2 text-xl font-medium">{d.has_drift?'Structural changes detected':'No structural drift detected'}</div><p className="mt-2 text-sm text-white/40">{data.message}</p></div><span className={`rounded-full border px-3 py-1.5 text-[10px] uppercase tracking-widest ${d.has_drift?'border-amber-300/20 bg-amber-300/10 text-amber-200':'border-emerald-300/20 bg-emerald-300/10 text-emerald-200'}`}>{d.has_drift?'Drift':'Stable'}</span></div></div><div className="mt-6 grid gap-4 xl:grid-cols-3"><ListCard title="Added modules" items={d.module_drift.added_modules}/><ListCard title="Removed modules" items={d.module_drift.removed_modules}/><ListCard title="Changed dependencies" items={d.dependency_drift.changed_modules.map(x=>x.file)}/></div></>:<div className="mt-6 rounded-3xl border border-amber-300/10 bg-amber-300/[.04] p-6"><div className="text-sm font-medium text-amber-100">Comparison is not configured yet</div><p className="mt-2 text-sm leading-6 text-amber-100/45">{data.message}</p></div>}<div className="mt-6 flex flex-wrap gap-2"><Link href="/architecture" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2.5 text-xs text-white/70">Open architecture</Link><Link href="/reports" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2.5 text-xs text-white/70">Open report</Link></div></>}</div></section></div></main>;
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><div className="text-[9px] uppercase tracking-[.18em] text-white/25">{label}</div><div className="mt-4 text-2xl font-semibold tracking-tight">{value}</div></div>}
function ListCard({title,items}:{title:string;items:string[]}){return <div className="rounded-2xl border border-white/[.08] bg-white/[.02] p-5"><div className="text-sm font-medium">{title}</div><div className="mt-4 space-y-2">{items.length?items.slice(0,12).map(x=><div key={x} className="rounded-lg border border-white/[.06] bg-black/20 px-3 py-2 font-mono text-[11px] text-white/50 break-all">{x}</div>):<div className="text-xs text-white/25">None</div>}</div></div>}
function Alert({text}:{text:string}){return <div className="rounded-2xl border border-red-300/10 bg-red-400/[.05] p-5 text-sm text-red-100/70">{text}</div>}
function Skeleton(){return <div className="h-40 animate-pulse rounded-3xl bg-white/[.03]"/>}
